# Generated by Django 3.1.6 on 2021-04-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclestatus',
            old_name='json',
            new_name='vehicleid',
        ),
    ]
