# Generated by Django 3.1.6 on 2021-04-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210422_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclestatus',
            name='vs',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
