# Generated by Django 3.1.6 on 2021-04-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vehiclestatus_vs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclestatus',
            name='vs',
        ),
        migrations.AddField(
            model_name='vehiclestatus',
            name='payload',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiclestatus',
            name='vehicleid',
            field=models.CharField(max_length=11),
        ),
    ]
