# Generated by Django 3.1.7 on 2021-04-28 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210426_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclestatus',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
