# Generated by Django 3.1.7 on 2021-05-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210525_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclestatus',
            name='payload',
        ),
    ]
