# Generated by Django 3.1.7 on 2021-06-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210616_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclestatus',
            name='accu_spanning',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
