# Generated by Django 3.1.7 on 2021-05-26 13:57

from django.db import migrations
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vehicle_ids',
            field=user_profile.models.UpperCaseCharField(max_length=240, null=True),
        ),
    ]
