# Generated by Django 3.1.7 on 2021-04-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210426_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='vehicleid',
            new_name='vehicle_id',
        ),
    ]
