# Generated by Django 3.1.7 on 2021-05-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
