# Generated by Django 3.1.7 on 2021-05-26 10:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_remove_profile_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vehicle_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11, null=True), default=0, size=None),
            preserve_default=False,
        ),
    ]
