# Generated by Django 3.1.7 on 2021-05-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20210526_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vehicle_ids',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
